//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Tareas.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public Materias()
        {
            this.Tareas = new HashSet<Tareas>();
            this.TipoMaterias = new HashSet<TipoMateria>();
        }
    
        public int IdMateria { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Tareas> Tareas { get; set; }
        public virtual ICollection<TipoMateria> TipoMaterias { get; set; }
    }
}
