//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Tareas.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMateria
    {
        public TipoMateria()
        {
            this.Materia = new HashSet<Materias>();
        }
    
        public int IdTipoMateria { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Materias> Materia { get; set; }
    }
}
